### ISSUE TITLE
Explore MUI Core as front-end framework 

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#1]
This looks super-promising. Let's ensure that it can handle the basic flows that we've got in the [rough concepts](https://www.figma.com/file/sNkqgWQjjx9GSiTqqFWtXr/Stemstr?node-id=53103%3A27794&t=vuB43Xa6Q1L6MUwF-1) if so, then i think we've got ourselves a contender.

**Comment by michaelhall923** [comment]
Decided to go with Mantine. It's free, open source and mostly unopinionated.
