### ISSUE TITLE
Upload polish

### ISSUE THREAD

**Issue by bndw** [stemstr/Client#12]
### Validation
- [x] Only accept audio file types. We probably want `accept="audio/*"` [HTML attribute: accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers)
- [x] Redirect to `/login` on drag+drop/upload button click if the user is not logged in
- [x] Once a file has been selected, raise an error if the file is too large. [size attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#getting_information_on_selected_files)

### Handle upload errors
- [x] If the API returns a `401` status code (Unauthorized), it means there was no `pk` field in the upload form. Redirect the user to /login, although this should have previously been handled in the Validation section.
- [x] If the API returns a `400` status code (Bad Request), display the error message in the response body.
- [x] If the API returns a `500` status code (Server error), display a generic message informing the user to try again later.

### Other
- [x] Disable the "Share" button until the file upload has successfully completed
- [x] Show a loading state while the upload is happening so the user knows something is happening. Maybe we could animate the waveform with a sin wave?

**Comment by michaelhall923** [comment]
What's the file size limit?

**Comment by bndw** [comment]
Let's pick an arbitrary size. According to [this calculator](https://www.colincrawley.com/audio-file-size-calculator/), an uncompressed 10 minute audio file would be 100MB. That seems like a reasonable starting point.
