### ISSUE TITLE
commenting seems broken

### ISSUE THREAD

**Issue by SamSamskies** [stemstr/Client#127]
just tried to comment [on this](https://stemstr-client-ten.vercel.app/thread/474f33734fead3e4078c0b1c85dce9d8422c136fe0f592232c26f1c5a6bf7d76) and nothing happens. popped open the dev console and there's this error.

<img width="672" alt="Screenshot 2023-06-27 at 12 34 56 AM" src="https://github.com/stemstr/Client/assets/3655410/aeadfc76-02f4-4b6f-b454-3ff707160e73">

**Comment by michaelhall923** [comment]
i think this is causing it https://github.com/stemstr/Client/blob/036e6744110d01e16244e4c32d55feac13ad1bad/ndk/utils.tsx#L76
