### ISSUE TITLE
a user should only be able to like a note once

### ISSUE THREAD

**Issue by SamSamskies** [stemstr/Client#132]
i'm able to like a note as many times as i want. i don't think that should be allowed. currently, you can like your own post a million times just by clicking it over and over again.

**Comment by michaelhall923** [comment]
so we need to make reaction counts unique by pubkey

**Comment by SamSamskies** [comment]
This is an easy fix cause we're already keeping track if the user liked a note.

**Comment by SamSamskies** [comment]
It's like a one line fix. I can just fix it rn actually.
