### ISSUE TITLE
No wallet, shift note actions

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#164]
When there isn't a wallet connected to a users account, let's shift the note actions so there isn't a blank space ![image](https://github.com/stemstr/Client/assets/2218506/47289bd3-6336-4d23-b083-8b9470742c75)

**Comment by SamSamskies** [comment]
what do you mean by shift the note actions? just move the heart icon over to the right edge?

have we thought about doing it like how a lot of the other nostr clients do it? the most common pattern i've seen is the icons are all left aligned in the row with a fixed amount of space. that's simpler and imo it looks better.

**Comment by rockymedure** [comment]
Heart to the right. I’d like to try to right align because it’s closer to
the thumb
