### ISSUE TITLE
Sign Up / Login Page

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#19]
- [x] update pitch from "The sounds of music" to ["Where music gets made"](https://www.figma.com/file/cyFAijooLoe3ssiUxryRvf/Stemstr-App?node-id=2390-64161&t=uV5zbxIFmWGvCHJu-4)
- [x] no need to have the navbar here 
- [x] Learn more should hyperlink to https://stemstr.app
- [x] can we detect browser extension to show/hide connect? 
- [x] Fix margins on login page (content area should be wider as per design)

**Comment by knowerlittle** [comment]
@rockymedure 
Fix margins on login page (content area should be wider as per design) - included in this PR: https://github.com/stemstr/Client/pull/49

Re: Learn more should hyperlink to https://stemstr.app/
The link is broken - when do you see this page being up?

**Comment by knowerlittle** [comment]
PR includes linking to https://www.stemstr.app/ now
