### ISSUE TITLE
Mobile file upload

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#24]
Looks as though I'm unable to upload files from iOS. Circled is a .wav that was downloaded from Drive and saved into Files. ![image](https://user-images.githubusercontent.com/2218506/230886965-7f6b10bb-18dd-452c-8738-12ec1429e694.jpeg)

**Comment by michaelhall923** [comment]
It might be that iOS safari doesn't understand accept="audio/*", and so I will have to use accept="audio/mp3, audio/wav, etc."
