### ISSUE TITLE
Update header on mobile Sign Up / Login page

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#33]
We can save vertical space by making the header go from vertically oriented (as it is on desktop) to horizontally oriented. Mocks attached for reference. 

![image](https://user-images.githubusercontent.com/2218506/231521603-5690f3a6-98bc-4f3d-acba-9e8491c68c68.png)

**Comment by michaelhall923** [comment]
Figma link: https://www.figma.com/file/cyFAijooLoe3ssiUxryRvf/Stemstr-App?node-id=2390-64095&t=Is7nW5f1ZolR6T90-4

**Comment by Anurag-Raut** [comment]
I have made the changes ,can you please review PR #37
