### ISSUE TITLE
Define theme breakpoints

### ISSUE THREAD

**Issue by michaelhall923** [stemstr/Client#39]
We can probably get by with just one breakpoint that defines the transition between mobile and desktop. Here are the default presets for reference:
```
breakpoints: {
  xs: 576px,
  sm: 768px,
  md: 992px,
  lg: 1200px,
  xl: 1400px,
},
```

**Comment by michaelhall923** [comment]
xs: 480px

**Comment by knowerlittle** [comment]
Breakpoints included in this PR: https://github.com/stemstr/Client/pull/49
