### ISSUE TITLE
Render notes with rich content

### ISSUE THREAD

**Issue by bndw** [stemstr/Client#47]
We should render different types of content within notes such as:

- [x] URLs should be rendered as clickable hyperlinks
- [x] Mentions
- [ ] Images?

**Comment by michaelhall923** [comment]
More broadly, need to devise a system for parsing notes. Maybe a function that takes the raw note and returns an array of components.

```
function parseNoteContent(content: string): React.ReactElement[]
```

**Comment by rockymedure** [comment]
Tagging peeps with @ would be a really nice addition. Can we also include the open graph image of someone drops in a link?

**Comment by michaelhall923** [comment]
Yeah. all these things could be aggregated on one issue probably. Links, images, previews, embeds, mentions, etc.

**Comment by rockymedure** [comment]
+1

**Comment by bndw** [comment]
Updated the issue title + description to serve as a meta issue for "rich notes"
