### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by michaelhall923** [stemstr/Client#51]
Not sure what's causing this.
![Screenshot 2023-04-15 at 10 35 11 PM](https://user-images.githubusercontent.com/40177960/232263745-f59e305a-2bc7-4e28-bd23-a4b324273d4f.png)

**Comment by Hi-Pyncho** [comment]
@michaelhall923 

can you show your code? it's better if you recreate your problem in any online js sandboxes like [this](https://codesandbox.io/)

**Comment by michaelhall923** [comment]
yeah i haven't seen it in a while for whatever reason
