### ISSUE TITLE
Cache nip05 in memory

### ISSUE THREAD

**Issue by michaelhall923** [stemstr/Client#64]
No need to make the nip05 request for the same user a zillion different times on the same page load. useNip05 hook should be modified so that it remembers the result until page is refreshed. Can use redux or jotai (like in useProfile). These libraries may be redundant but that's a separate issue. Would recommend using redux.

**Comment by SamSamskies** [comment]
Also need this for caching the user profile.

**Comment by SamSamskies** [comment]
> Can use redux or jotai (like in useProfile)

Was the caching removed when updating to NDK?

**Comment by michaelhall923** [comment]
yeah this issue is irrelevant now.

See https://github.com/stemstr/Client/issues/85
