### ISSUE TITLE
Relative note time missing if ~1day old

### ISSUE THREAD

**Issue by bndw** [stemstr/Client#66]
https://github.com/stemstr/Client/pull/65 changed note times from long form strings to short form strings like "23 minutes ago" to "23m". But this seems to have broken if the note's timestamp is ~1day.

For example, notes with a timestamp < 1 day work:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/4248167/233222974-7209cb7f-8eb9-496b-b55c-82c703c230eb.png">

And notes with a timestamp > 1 day work:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/4248167/233223079-f6d50a81-fdc3-4d17-a596-98ac306f2087.png">

But notes with a timestamp of ~1day ago are missing their relative time:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/4248167/233223125-a6ddf399-cf77-4424-b292-19e1cc562d7e.png">

**Comment by SamSamskies** [comment]
Seems like this issue is resolved.

![Screenshot 2023-04-29 at 2 14 15 PM](https://user-images.githubusercontent.com/3655410/235320350-b1ec2e38-cf80-4346-be5f-9e155b050ef6.png)
