### ISSUE TITLE
Auto-fetch latest events in feed

### ISSUE THREAD

**Issue by michaelhall923** [stemstr/Client#79]
Currently you have to refresh page to get the latest notes

**Comment by SamSamskies** [comment]
as a user, i wouldn't want new events to stream in. would it be possible to get some designs to do something like this?

![Screenshot 2023-06-19 at 7 56 19 PM](https://github.com/stemstr/Client/assets/3655410/dd1bb483-7ac8-4992-a277-3d36574a3774)

**Comment by michaelhall923** [comment]
@robagreda @rockymedure
