### ISSUE TITLE
Replying to name missing

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Client#99]
Showing as undefined when commenting ![image](https://github.com/stemstr/Client/assets/2218506/6d1b924a-ea76-41bf-98cf-ab86f1d516a5)

**Comment by SamSamskies** [comment]
I think this is the source of the bug.

https://github.com/stemstr/Client/blob/2866e8e08e3c36c645e9171038e91701542fb261/components/PostSheet/PostSheet.js#L140

`replyingTo` is typed as an `Event` and an `Event` doesn't have a `profile` property. I looked at the code and I think the type is wrong. We're actually passing in an `NDKEvent`. That also doesn't have a `profile` property, but we're able to access the profile using the `NDKEvent`.

`PostSheet` should probably be refactored to TypeScript when fixing this. There may be other bugs in it.

**Comment by rockymedure** [comment]
Thanks for looking into this, Sam!

**Comment by SamSamskies** [comment]
I actually stumbled across this bug as I was getting started on zaps. Let me actually fix this first. I think it'll be a quick fix.

**Comment by rockymedure** [comment]
🙏
